openapi: "3.0.0"
info:
  title: 'Authentication Service'
  version: "0.1.0"

paths:
  /api/v1/register:
    post:
      summary: "Register a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "User registered"
        '400':
          description: "Bad request"

  /api/v1/login:
    post:
      summary: "Login user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "Logged in"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '401':
          description: "Unauthorized"

  /api/v1/refresh-token:
    post:
      summary: "Refresh access token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: "Access token refreshed"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '401':
          description: "Unauthorized"

  /api/v1/logout:
    post:
      summary: "User logout"
      responses:
        '200':
          description: "Logged out"
        '401':
          description: "Unauthorized"

paths:
  /api/v1/roles:
    post:
      summary: "Create a new role"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role_name:
                  type: string
      responses:
        '200':
          description: "Role created"
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

    get:
      summary: "Get all roles"
      responses:
        '200':
          description: "Roles retrieved successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    role_name:
                      type: string
        '401':
          description: "Unauthorized"

  /api/v1/roles/{role_name}:
    post:
      summary: "Add a new permission to a role"
      parameters:
        - in: path
          required: True
          name: role_name
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                permission_name:
                  type: string
      responses:
        '200':
          description: "Permission added to role"
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"
    put:
      summary: "Update a role"
      parameters:
        - in: path
          required: True
          name: role_name
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role_name:
                  type: string
      responses:
        '200':
          description: "Role updated"
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"
    delete:
      summary: "Delete a role"
      parameters:
        - in: path
          required: True
          name: role_name
          schema:
            type: string
      responses:
        '200':
          description: "Role deleted"
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

  /api/v1/roles/user/{user_id}:
    put:
      summary: "Update roles of a user"
      parameters:
        - in: path
          required: True
          name: user_id
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roles:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: "Roles updated successfully"
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"
    get:
      summary: "Get all roles of a user"
      parameters:
        - in: path
          required: True
          name: user_id
          schema:
            type: integer
      responses:
        '200':
          description: "Roles retrieved successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    role_name:
                      type: string
        '401':
          description: "Unauthorized"


paths:
  /api/v1/me/login-history:
    get:
      summary: "Get user login history"
      responses:
        '200':
          description: "User login history retrieved successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    login_time:
                      format: date-time
                    user_agent:
                      format: string
                    ip_address:
                      format: string
        '401':
          description: "Unauthorized"

  /api/v1/me/permissions:
    get:
      summary: "Get user permissions"
      responses:
        '200':
          description: "User permissions retrieved successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    permission_name:
                      format: string
        '401':
          description: "Unauthorized"

  /api/v1/me/:
    get:
      summary: "Get user information"
      responses:
        '200':
          description: "User information retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    format: string
                  email:
                    format: string
                  first_name:
                    format: string
                  last_name:
                    format: string
                  phone_number:
                    format: string
                  address:
                    format: string
                  city:
                    format: string
                  country:
                    format: string
                  postal_code:
                    format: string
        '401':
          description: "Unauthorized"
    post:
        summary: "Update user information"
        requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      format: string
                    email:
                      format: string
                    first_name:
                      format: string
                    last_name:
                      format: string
                    phone_number:
                      format: string
                    address:
                      format: string
                    city:
                      format: string
                    country:
                      format: string
                    postal_code:
                      format: string
        responses:
            '200':
              description: "User information updated successfully"
            '400':
              description: "Bad request"
            '401':
              description: "Unauthorized"
